owner: semo94
repo: breadthwise-upptime

sites:
  - name: Breadthwise API
    url: https://api.breadthwise.ca/health
  - name: Breadthwise Web App
    url: https://app.breadthwise.ca

schedule: "*/10 * * * *"  # every 10 minutes

status-website:
  name: Breadthwise Status
  introTitle: "Welcome to Breadthwise Status"
  introMessage: "Real-time monitoring of all Breadthwise services."
  logo: https://app.breadthwise.ca/assets/assets/images/icon.04220ceef610db20fe513e6a4fc6f015.png
  favicon: https://breadthwise.ca/favicon.ico
  theme: dark
  navbar:
    - title: Home
      href: /
    - title: Docs
      href: https://github.com/semo94/the-architect/blob/main/README.md
